package com.ocr.dao.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table breath_report
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BreathReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.patient_name
     *
     * @mbg.generated
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.determination_date
     *
     * @mbg.generated
     */
    private Date determinationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.temperature
     *
     * @mbg.generated
     */
    private BigDecimal temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.height
     *
     * @mbg.generated
     */
    private BigDecimal height;

    /**
     * Database Column Remarks:
     *   ºÏ≤È’ﬂ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.inspector
     *
     * @mbg.generated
     */
    private String inspector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.weight
     *
     * @mbg.generated
     */
    private BigDecimal weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.humidity
     *
     * @mbg.generated
     */
    private BigDecimal humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.pressure
     *
     * @mbg.generated
     */
    private BigDecimal pressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.BSA
     *
     * @mbg.generated
     */
    private BigDecimal bsa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.building
     *
     * @mbg.generated
     */
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.determination_type
     *
     * @mbg.generated
     */
    private String determinationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breath_report.craete_time
     *
     * @mbg.generated
     */
    private Date craeteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.id
     *
     * @return the value of breath_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.id
     *
     * @param id the value for breath_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.file_name
     *
     * @return the value of breath_report.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.file_name
     *
     * @param fileName the value for breath_report.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.code
     *
     * @return the value of breath_report.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.code
     *
     * @param code the value for breath_report.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.patient_name
     *
     * @return the value of breath_report.patient_name
     *
     * @mbg.generated
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.patient_name
     *
     * @param patientName the value for breath_report.patient_name
     *
     * @mbg.generated
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName == null ? null : patientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.determination_date
     *
     * @return the value of breath_report.determination_date
     *
     * @mbg.generated
     */
    public Date getDeterminationDate() {
        return determinationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.determination_date
     *
     * @param determinationDate the value for breath_report.determination_date
     *
     * @mbg.generated
     */
    public void setDeterminationDate(Date determinationDate) {
        this.determinationDate = determinationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.temperature
     *
     * @return the value of breath_report.temperature
     *
     * @mbg.generated
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.temperature
     *
     * @param temperature the value for breath_report.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.age
     *
     * @return the value of breath_report.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.age
     *
     * @param age the value for breath_report.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.height
     *
     * @return the value of breath_report.height
     *
     * @mbg.generated
     */
    public BigDecimal getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.height
     *
     * @param height the value for breath_report.height
     *
     * @mbg.generated
     */
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.inspector
     *
     * @return the value of breath_report.inspector
     *
     * @mbg.generated
     */
    public String getInspector() {
        return inspector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.inspector
     *
     * @param inspector the value for breath_report.inspector
     *
     * @mbg.generated
     */
    public void setInspector(String inspector) {
        this.inspector = inspector == null ? null : inspector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.weight
     *
     * @return the value of breath_report.weight
     *
     * @mbg.generated
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.weight
     *
     * @param weight the value for breath_report.weight
     *
     * @mbg.generated
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.sex
     *
     * @return the value of breath_report.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.sex
     *
     * @param sex the value for breath_report.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.humidity
     *
     * @return the value of breath_report.humidity
     *
     * @mbg.generated
     */
    public BigDecimal getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.humidity
     *
     * @param humidity the value for breath_report.humidity
     *
     * @mbg.generated
     */
    public void setHumidity(BigDecimal humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.pressure
     *
     * @return the value of breath_report.pressure
     *
     * @mbg.generated
     */
    public BigDecimal getPressure() {
        return pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.pressure
     *
     * @param pressure the value for breath_report.pressure
     *
     * @mbg.generated
     */
    public void setPressure(BigDecimal pressure) {
        this.pressure = pressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.BSA
     *
     * @return the value of breath_report.BSA
     *
     * @mbg.generated
     */
    public BigDecimal getBsa() {
        return bsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.BSA
     *
     * @param bsa the value for breath_report.BSA
     *
     * @mbg.generated
     */
    public void setBsa(BigDecimal bsa) {
        this.bsa = bsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.subject
     *
     * @return the value of breath_report.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.subject
     *
     * @param subject the value for breath_report.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.building
     *
     * @return the value of breath_report.building
     *
     * @mbg.generated
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.building
     *
     * @param building the value for breath_report.building
     *
     * @mbg.generated
     */
    public void setBuilding(String building) {
        this.building = building == null ? null : building.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.determination_type
     *
     * @return the value of breath_report.determination_type
     *
     * @mbg.generated
     */
    public String getDeterminationType() {
        return determinationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.determination_type
     *
     * @param determinationType the value for breath_report.determination_type
     *
     * @mbg.generated
     */
    public void setDeterminationType(String determinationType) {
        this.determinationType = determinationType == null ? null : determinationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breath_report.craete_time
     *
     * @return the value of breath_report.craete_time
     *
     * @mbg.generated
     */
    public Date getCraeteTime() {
        return craeteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breath_report.craete_time
     *
     * @param craeteTime the value for breath_report.craete_time
     *
     * @mbg.generated
     */
    public void setCraeteTime(Date craeteTime) {
        this.craeteTime = craeteTime;
    }
}