package com.ocr.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OcrBaseTabledataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public OcrBaseTabledataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIndexIsNull() {
            addCriterion("index is null");
            return (Criteria) this;
        }

        public Criteria andIndexIsNotNull() {
            addCriterion("index is not null");
            return (Criteria) this;
        }

        public Criteria andIndexEqualTo(Integer value) {
            addCriterion("index =", value, "index");
            return (Criteria) this;
        }

        public Criteria andIndexNotEqualTo(Integer value) {
            addCriterion("index <>", value, "index");
            return (Criteria) this;
        }

        public Criteria andIndexGreaterThan(Integer value) {
            addCriterion("index >", value, "index");
            return (Criteria) this;
        }

        public Criteria andIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("index >=", value, "index");
            return (Criteria) this;
        }

        public Criteria andIndexLessThan(Integer value) {
            addCriterion("index <", value, "index");
            return (Criteria) this;
        }

        public Criteria andIndexLessThanOrEqualTo(Integer value) {
            addCriterion("index <=", value, "index");
            return (Criteria) this;
        }

        public Criteria andIndexIn(List<Integer> values) {
            addCriterion("index in", values, "index");
            return (Criteria) this;
        }

        public Criteria andIndexNotIn(List<Integer> values) {
            addCriterion("index not in", values, "index");
            return (Criteria) this;
        }

        public Criteria andIndexBetween(Integer value1, Integer value2) {
            addCriterion("index between", value1, value2, "index");
            return (Criteria) this;
        }

        public Criteria andIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("index not between", value1, value2, "index");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(BigDecimal value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(BigDecimal value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(BigDecimal value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(BigDecimal value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<BigDecimal> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<BigDecimal> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andBmcIsNull() {
            addCriterion("bmc is null");
            return (Criteria) this;
        }

        public Criteria andBmcIsNotNull() {
            addCriterion("bmc is not null");
            return (Criteria) this;
        }

        public Criteria andBmcEqualTo(BigDecimal value) {
            addCriterion("bmc =", value, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcNotEqualTo(BigDecimal value) {
            addCriterion("bmc <>", value, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcGreaterThan(BigDecimal value) {
            addCriterion("bmc >", value, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bmc >=", value, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcLessThan(BigDecimal value) {
            addCriterion("bmc <", value, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bmc <=", value, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcIn(List<BigDecimal> values) {
            addCriterion("bmc in", values, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcNotIn(List<BigDecimal> values) {
            addCriterion("bmc not in", values, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bmc between", value1, value2, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bmc not between", value1, value2, "bmc");
            return (Criteria) this;
        }

        public Criteria andBmdIsNull() {
            addCriterion("bmd is null");
            return (Criteria) this;
        }

        public Criteria andBmdIsNotNull() {
            addCriterion("bmd is not null");
            return (Criteria) this;
        }

        public Criteria andBmdEqualTo(BigDecimal value) {
            addCriterion("bmd =", value, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdNotEqualTo(BigDecimal value) {
            addCriterion("bmd <>", value, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdGreaterThan(BigDecimal value) {
            addCriterion("bmd >", value, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bmd >=", value, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdLessThan(BigDecimal value) {
            addCriterion("bmd <", value, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bmd <=", value, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdIn(List<BigDecimal> values) {
            addCriterion("bmd in", values, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdNotIn(List<BigDecimal> values) {
            addCriterion("bmd not in", values, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bmd between", value1, value2, "bmd");
            return (Criteria) this;
        }

        public Criteria andBmdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bmd not between", value1, value2, "bmd");
            return (Criteria) this;
        }

        public Criteria andTScoreIsNull() {
            addCriterion("t_score is null");
            return (Criteria) this;
        }

        public Criteria andTScoreIsNotNull() {
            addCriterion("t_score is not null");
            return (Criteria) this;
        }

        public Criteria andTScoreEqualTo(BigDecimal value) {
            addCriterion("t_score =", value, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreNotEqualTo(BigDecimal value) {
            addCriterion("t_score <>", value, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreGreaterThan(BigDecimal value) {
            addCriterion("t_score >", value, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("t_score >=", value, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreLessThan(BigDecimal value) {
            addCriterion("t_score <", value, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("t_score <=", value, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreIn(List<BigDecimal> values) {
            addCriterion("t_score in", values, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreNotIn(List<BigDecimal> values) {
            addCriterion("t_score not in", values, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t_score between", value1, value2, "tScore");
            return (Criteria) this;
        }

        public Criteria andTScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t_score not between", value1, value2, "tScore");
            return (Criteria) this;
        }

        public Criteria andPrIsNull() {
            addCriterion("pr is null");
            return (Criteria) this;
        }

        public Criteria andPrIsNotNull() {
            addCriterion("pr is not null");
            return (Criteria) this;
        }

        public Criteria andPrEqualTo(BigDecimal value) {
            addCriterion("pr =", value, "pr");
            return (Criteria) this;
        }

        public Criteria andPrNotEqualTo(BigDecimal value) {
            addCriterion("pr <>", value, "pr");
            return (Criteria) this;
        }

        public Criteria andPrGreaterThan(BigDecimal value) {
            addCriterion("pr >", value, "pr");
            return (Criteria) this;
        }

        public Criteria andPrGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pr >=", value, "pr");
            return (Criteria) this;
        }

        public Criteria andPrLessThan(BigDecimal value) {
            addCriterion("pr <", value, "pr");
            return (Criteria) this;
        }

        public Criteria andPrLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pr <=", value, "pr");
            return (Criteria) this;
        }

        public Criteria andPrIn(List<BigDecimal> values) {
            addCriterion("pr in", values, "pr");
            return (Criteria) this;
        }

        public Criteria andPrNotIn(List<BigDecimal> values) {
            addCriterion("pr not in", values, "pr");
            return (Criteria) this;
        }

        public Criteria andPrBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pr between", value1, value2, "pr");
            return (Criteria) this;
        }

        public Criteria andPrNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pr not between", value1, value2, "pr");
            return (Criteria) this;
        }

        public Criteria andZScoreIsNull() {
            addCriterion("z_score is null");
            return (Criteria) this;
        }

        public Criteria andZScoreIsNotNull() {
            addCriterion("z_score is not null");
            return (Criteria) this;
        }

        public Criteria andZScoreEqualTo(BigDecimal value) {
            addCriterion("z_score =", value, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreNotEqualTo(BigDecimal value) {
            addCriterion("z_score <>", value, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreGreaterThan(BigDecimal value) {
            addCriterion("z_score >", value, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("z_score >=", value, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreLessThan(BigDecimal value) {
            addCriterion("z_score <", value, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("z_score <=", value, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreIn(List<BigDecimal> values) {
            addCriterion("z_score in", values, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreNotIn(List<BigDecimal> values) {
            addCriterion("z_score not in", values, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("z_score between", value1, value2, "zScore");
            return (Criteria) this;
        }

        public Criteria andZScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("z_score not between", value1, value2, "zScore");
            return (Criteria) this;
        }

        public Criteria andAmIsNull() {
            addCriterion("am is null");
            return (Criteria) this;
        }

        public Criteria andAmIsNotNull() {
            addCriterion("am is not null");
            return (Criteria) this;
        }

        public Criteria andAmEqualTo(BigDecimal value) {
            addCriterion("am =", value, "am");
            return (Criteria) this;
        }

        public Criteria andAmNotEqualTo(BigDecimal value) {
            addCriterion("am <>", value, "am");
            return (Criteria) this;
        }

        public Criteria andAmGreaterThan(BigDecimal value) {
            addCriterion("am >", value, "am");
            return (Criteria) this;
        }

        public Criteria andAmGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("am >=", value, "am");
            return (Criteria) this;
        }

        public Criteria andAmLessThan(BigDecimal value) {
            addCriterion("am <", value, "am");
            return (Criteria) this;
        }

        public Criteria andAmLessThanOrEqualTo(BigDecimal value) {
            addCriterion("am <=", value, "am");
            return (Criteria) this;
        }

        public Criteria andAmIn(List<BigDecimal> values) {
            addCriterion("am in", values, "am");
            return (Criteria) this;
        }

        public Criteria andAmNotIn(List<BigDecimal> values) {
            addCriterion("am not in", values, "am");
            return (Criteria) this;
        }

        public Criteria andAmBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("am between", value1, value2, "am");
            return (Criteria) this;
        }

        public Criteria andAmNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("am not between", value1, value2, "am");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}