package com.ocr.dao.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ocr_base_tabledata
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OcrBaseTabledata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.index
     *
     * @mbg.generated
     */
    private Integer index;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     * Database Column Remarks:
     *   cm2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.area
     *
     * @mbg.generated
     */
    private BigDecimal area;

    /**
     * Database Column Remarks:
     *   单位：g
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.bmc
     *
     * @mbg.generated
     */
    private BigDecimal bmc;

    /**
     * Database Column Remarks:
     *   单位：g/cm2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.bmd
     *
     * @mbg.generated
     */
    private BigDecimal bmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.t_score
     *
     * @mbg.generated
     */
    private BigDecimal tScore;

    /**
     * Database Column Remarks:
     *   单位：%
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.pr
     *
     * @mbg.generated
     */
    private BigDecimal pr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.z_score
     *
     * @mbg.generated
     */
    private BigDecimal zScore;

    /**
     * Database Column Remarks:
     *   单位：%
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_base_tabledata.am
     *
     * @mbg.generated
     */
    private BigDecimal am;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.id
     *
     * @return the value of ocr_base_tabledata.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.id
     *
     * @param id the value for ocr_base_tabledata.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.index
     *
     * @return the value of ocr_base_tabledata.index
     *
     * @mbg.generated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.index
     *
     * @param index the value for ocr_base_tabledata.index
     *
     * @mbg.generated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.region
     *
     * @return the value of ocr_base_tabledata.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.region
     *
     * @param region the value for ocr_base_tabledata.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.area
     *
     * @return the value of ocr_base_tabledata.area
     *
     * @mbg.generated
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.area
     *
     * @param area the value for ocr_base_tabledata.area
     *
     * @mbg.generated
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.bmc
     *
     * @return the value of ocr_base_tabledata.bmc
     *
     * @mbg.generated
     */
    public BigDecimal getBmc() {
        return bmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.bmc
     *
     * @param bmc the value for ocr_base_tabledata.bmc
     *
     * @mbg.generated
     */
    public void setBmc(BigDecimal bmc) {
        this.bmc = bmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.bmd
     *
     * @return the value of ocr_base_tabledata.bmd
     *
     * @mbg.generated
     */
    public BigDecimal getBmd() {
        return bmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.bmd
     *
     * @param bmd the value for ocr_base_tabledata.bmd
     *
     * @mbg.generated
     */
    public void setBmd(BigDecimal bmd) {
        this.bmd = bmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.t_score
     *
     * @return the value of ocr_base_tabledata.t_score
     *
     * @mbg.generated
     */
    public BigDecimal gettScore() {
        return tScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.t_score
     *
     * @param tScore the value for ocr_base_tabledata.t_score
     *
     * @mbg.generated
     */
    public void settScore(BigDecimal tScore) {
        this.tScore = tScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.pr
     *
     * @return the value of ocr_base_tabledata.pr
     *
     * @mbg.generated
     */
    public BigDecimal getPr() {
        return pr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.pr
     *
     * @param pr the value for ocr_base_tabledata.pr
     *
     * @mbg.generated
     */
    public void setPr(BigDecimal pr) {
        this.pr = pr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.z_score
     *
     * @return the value of ocr_base_tabledata.z_score
     *
     * @mbg.generated
     */
    public BigDecimal getzScore() {
        return zScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.z_score
     *
     * @param zScore the value for ocr_base_tabledata.z_score
     *
     * @mbg.generated
     */
    public void setzScore(BigDecimal zScore) {
        this.zScore = zScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_base_tabledata.am
     *
     * @return the value of ocr_base_tabledata.am
     *
     * @mbg.generated
     */
    public BigDecimal getAm() {
        return am;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_base_tabledata.am
     *
     * @param am the value for ocr_base_tabledata.am
     *
     * @mbg.generated
     */
    public void setAm(BigDecimal am) {
        this.am = am;
    }
}