package com.ocr.dao.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ocr_bone
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OcrBone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *  
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.BMD
     *
     * @mbg.generated
     */
    private BigDecimal bmd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.PR
     *
     * @mbg.generated
     */
    private Integer pr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.part
     *
     * @mbg.generated
     */
    private String part;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     * 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_bone.insert_date
     *
     * @mbg.generated
     */
    private Date insertDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.id
     *
     * @return the value of ocr_bone.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.id
     *
     * @param id the value for ocr_bone.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.patient_id
     *
     * @return the value of ocr_bone.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.patient_id
     *
     * @param patientId the value for ocr_bone.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.BMD
     *
     * @return the value of ocr_bone.BMD
     *
     * @mbg.generated
     */
    public BigDecimal getBmd() {
        return bmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.BMD
     *
     * @param bmd the value for ocr_bone.BMD
     *
     * @mbg.generated
     */
    public void setBmd(BigDecimal bmd) {
        this.bmd = bmd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.PR
     *
     * @return the value of ocr_bone.PR
     *
     * @mbg.generated
     */
    public Integer getPr() {
        return pr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.PR
     *
     * @param pr the value for ocr_bone.PR
     *
     * @mbg.generated
     */
    public void setPr(Integer pr) {
        this.pr = pr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.part
     *
     * @return the value of ocr_bone.part
     *
     * @mbg.generated
     */
    public String getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.part
     *
     * @param part the value for ocr_bone.part
     *
     * @mbg.generated
     */
    public void setPart(String part) {
        this.part = part == null ? null : part.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.sex
     *
     * @return the value of ocr_bone.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.sex
     *
     * @param sex the value for ocr_bone.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.birthday
     *
     * @return the value of ocr_bone.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.birthday
     *
     * @param birthday the value for ocr_bone.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_bone.insert_date
     *
     * @return the value of ocr_bone.insert_date
     *
     * @mbg.generated
     */
    public Date getInsertDate() {
        return insertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_bone.insert_date
     *
     * @param insertDate the value for ocr_bone.insert_date
     *
     * @mbg.generated
     */
    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }
}