package com.ocr.dao.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pdf_linedata
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PdfLinedata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_linedata.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_linedata.pdf_id
     *
     * @mbg.generated
     */
    private Integer pdfId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_linedata.y_begin
     *
     * @mbg.generated
     */
    private Float yBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_linedata.x_begin
     *
     * @mbg.generated
     */
    private Float xBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_linedata.x_end
     *
     * @mbg.generated
     */
    private Float xEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pdf_linedata.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_linedata.id
     *
     * @return the value of pdf_linedata.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_linedata.id
     *
     * @param id the value for pdf_linedata.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_linedata.pdf_id
     *
     * @return the value of pdf_linedata.pdf_id
     *
     * @mbg.generated
     */
    public Integer getPdfId() {
        return pdfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_linedata.pdf_id
     *
     * @param pdfId the value for pdf_linedata.pdf_id
     *
     * @mbg.generated
     */
    public void setPdfId(Integer pdfId) {
        this.pdfId = pdfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_linedata.y_begin
     *
     * @return the value of pdf_linedata.y_begin
     *
     * @mbg.generated
     */
    public Float getyBegin() {
        return yBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_linedata.y_begin
     *
     * @param yBegin the value for pdf_linedata.y_begin
     *
     * @mbg.generated
     */
    public void setyBegin(Float yBegin) {
        this.yBegin = yBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_linedata.x_begin
     *
     * @return the value of pdf_linedata.x_begin
     *
     * @mbg.generated
     */
    public Float getxBegin() {
        return xBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_linedata.x_begin
     *
     * @param xBegin the value for pdf_linedata.x_begin
     *
     * @mbg.generated
     */
    public void setxBegin(Float xBegin) {
        this.xBegin = xBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_linedata.x_end
     *
     * @return the value of pdf_linedata.x_end
     *
     * @mbg.generated
     */
    public Float getxEnd() {
        return xEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_linedata.x_end
     *
     * @param xEnd the value for pdf_linedata.x_end
     *
     * @mbg.generated
     */
    public void setxEnd(Float xEnd) {
        this.xEnd = xEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pdf_linedata.text
     *
     * @return the value of pdf_linedata.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pdf_linedata.text
     *
     * @param text the value for pdf_linedata.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}