package com.ocr.dao.client;

import com.ocr.dao.model.BreathReport;
import com.ocr.dao.model.BreathReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BreathReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int insert(BreathReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int insertSelective(BreathReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    List<BreathReport> selectByExample(BreathReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    BreathReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BreathReport record, @Param("example") BreathReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BreathReport record, @Param("example") BreathReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BreathReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breath_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BreathReport record);
}