package com.ocr.dao.client;

import com.ocr.dao.model.OcrBaseTabledata;
import com.ocr.dao.model.OcrBaseTabledataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OcrBaseTabledataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int insert(OcrBaseTabledata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int insertSelective(OcrBaseTabledata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    List<OcrBaseTabledata> selectByExample(OcrBaseTabledataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    OcrBaseTabledata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OcrBaseTabledata record, @Param("example") OcrBaseTabledataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OcrBaseTabledata record, @Param("example") OcrBaseTabledataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OcrBaseTabledata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_base_tabledata
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OcrBaseTabledata record);
}