package com.ocr.dao.client;

import com.ocr.dao.model.Pdf;
import com.ocr.dao.model.PdfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PdfMapper {
	int selectMaxId();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int insert(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int insertSelective(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    List<Pdf> selectByExample(PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    Pdf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pdf record, @Param("example") PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pdf record, @Param("example") PdfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pdf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pdf
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pdf record);
}