spring:
  application:
    name: searching-service
  profiles:
    active: ou
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/data?characterEncoding=UTF-8
    username: root
    password: 123456
 
server:
  port: 9999
  tomcat:
    max-threads: 4

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
mybatis:
  mapper-locations: classpath:com/ocr/dao/sqlmap/*.xml
  type-aliases-package: com.ocr.dao.model
  
# 打印日志
logging:
  level:
    root: info
    com.ocr.dao.client: trace
    

